### ISSUE TITLE
--no-numbers and --dup-remove not working

### ISSUE THREAD

**Issue by gg5x** [rurapenthe/rurasort#2]
the commands --no-numbers and --dup-remove aren't removing / changing words they should be applying to.

**Comment by bitcrackcyber** [comment]
This is a known issue. The characters are not being detected correctly by Python so it often leaves numbers in the list. Will advise when its fixed.

**Comment by bitcrackcyber** [comment]
The bug in --no-numbers has been fixed and it appears to be working.

--dup-remove is working fine for me. Ensure that when using it, you first lowercase everything.

helloHello will NOT be detected by --dup-remove, only hellohello will be detected and changed to hello.

Thx.
